export function createViews(D) {
const activeFilter='Semua';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photo=(src,label,cls='',options={})=>src?`<img class="${cls}" src="${esc(src)}" alt="${esc(options.alt||label)}" loading="${options.eager?'eager':'lazy'}" ${options.eager?'fetchpriority="high"':''} decoding="async" width="${options.width||1280}" height="${options.height||720}" ${options.srcset?`srcset="${esc(options.srcset)}" sizes="(max-width: 700px) 88vw, (max-width: 1100px) 44vw, 600px"`:''}>`:`<div class="photo-empty ${cls}"><span class="frame-corner"></span><span class="monogram" aria-hidden="true">FM<span>／</span></span><small>${esc(label)}</small><span class="empty-caption">FOTO AKAN DITAMBAHKAN</span></div>`;
const toolGrid=path=>`<div class="tools">${D.tools.filter(t=>!path||t[2]===path).map(t=>`<div class="tool"><span style="--tool:${t[3]}">${esc(t[0])}</span><small>${esc(t[1])}</small></div>`).join('')}</div>`;
const card=p=>`<article class="project" data-category="${esc(p.category)}"><a href="/proyek/${p.id}/"><div class="project-visual ${p.path}">${p.image?photo(p.image,p.title,'',p):`<span class="project-symbol" aria-hidden="true">${p.type==='Fotografi'?'◉':p.type==='Web Programming'?'〈/〉':p.type==='Robotika'?'∞':p.type==='Microsoft Office'?'Aa':p.type==='Editing'?'◐':'Aa'}</span><small>PREVIEW ${esc(p.type.toUpperCase())}</small>`}<span class="open-project" aria-hidden="true">↗</span></div><div class="project-meta"><span>${esc(p.category)}</span><span>${p.sample?'Contoh konten':'Proyek UAS'}</span></div><h3>${esc(p.title)}</h3></a></article>`;
function header(route){const links=[['home','/','Beranda'],['creative','/creative/','Kreatif'],['tech','/tech/','Teknologi'],['about','/about/','Tentang'],['skills','/skills/','Skill & Tools']];return `<a class="skip-link" href="#main">Lewati navigasi</a><header><a class="brand" href="/" aria-label="Fajar Maulana — Beranda">fajar<span>.</span><small>MAULANA</small></a><nav id="navigation" aria-label="Navigasi utama">${links.map(([id,url,label])=>`<a ${route===id?'class="active" aria-current="page"':''} href="${url}">${label}</a>`).join('')}<a class="mobile-contact" href="/contact/">Kontak</a></nav><div class="header-actions"><button class="theme-toggle" type="button" aria-label="Tema: sistem. Klik untuk mengganti" title="Tema: sistem"><span aria-hidden="true">◐</span><span class="theme-label">Sistem</span></button><a class="nav-contact" href="/contact/">Mari berdiskusi <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-label="Buka navigasi" aria-controls="navigation" aria-expanded="false">☰</button></div></header>`;}
function socialLinks(compact=false){const links=[['Instagram',D.instagram],['WhatsApp',D.whatsapp?'https://wa.me/'+D.whatsapp:''],['Email',D.email?'mailto:'+D.email:'']];return `<div class="direct-socials ${compact?'compact':''}" aria-label="Kontak langsung">${links.map(([label,url])=>url?`<a href="${esc(url)}" ${label!=='Email'?'target="_blank" rel="noopener"':''}><span>${label}</span><span aria-hidden="true">↗</span></a>`:`<div class="social-pending"><span>${label}</span><small>Segera tersedia</small></div>`).join('')}</div>`;}
const footer=()=>`<footer><a class="brand" href="/">fajar<span>.</span></a>${socialLinks(true)}<small>© ${new Date().getFullYear()} Mochamad Fajar Maulana</small></footer>`;
const cta=(path='')=>`<section class="bottom-cta"><span class="eyebrow">MULAI DARI SEBUAH IDE</span><h2>Punya sesuatu<br>untuk diwujudkan?</h2><a class="button" href="/contact/${path?'?service='+path:''}">${path==='creative'?'Hubungi untuk jasa kreatif':path==='tech'?'Hubungi untuk jasa teknologi':'Mari bicarakan ide Anda'} ↗</a></section>`;
function home(){return `<main id="main" tabindex="-1"><section class="hero"><div><div class="eyebrow"><span class="short-line"></span> MAHASISWA · KREATIF · TEKNOLOGI</div><p class="intro">Halo, saya Mochamad Fajar Maulana.</p><h1><span class="text-line"><span>Kreatif di balik <em>lensa.</em></span></span><span class="text-line"><span>Presisi di balik <i>kode.</i></span></span></h1><p class="student-badge">${esc(D.education.status)} ${esc(D.education.major)}<br><span>${esc(D.education.institution)}</span></p><p class="hero-description">${esc(D.heroDescription)}</p><a class="text-link" href="#paths">Temukan yang Anda butuhkan <span>↓</span></a>${socialLinks()}</div><div class="hero-photo portrait-depth">${photo(D.formalPhoto,'Foto formal Mochamad Fajar Maulana','',{eager:true,width:640,height:800})}<span class="photo-label">01 / DI BALIK KARYA</span></div></section><section id="paths" class="paths"><a class="path-card creative" href="/creative/"><div class="path-top"><span>01 — VISUAL & CERITA</span><span class="path-icon">◉</span></div><h2>Jasa Media<br>& Kreatif<span>↗</span></h2><p>Menangkap momen. Membangun kesan.</p><div class="path-tags"><span>Fotografi</span><span>Editing</span><span>Desain Grafis</span></div><div class="path-link">Jelajahi karya kreatif <span>→</span></div></a><a class="path-card tech" href="/tech/"><div class="path-top"><span>02 — LOGIKA & SOLUSI</span><span class="path-icon">〈/〉</span></div><h2>Jasa Teknologi<br>& Programming<span>↗</span></h2><p>Menghubungkan ide dengan solusi nyata.</p><div class="path-tags"><span>Web Programming</span><span>Robotika</span><span>Microsoft Office</span></div><div class="path-link">Jelajahi karya teknologi <span>→</span></div></a></section><section class="about-strip"><span class="eyebrow">BELAJAR, BERKARYA, BERKOLABORASI</span><div><h2>Dari ruang kuliah<br>ke karya nyata.</h2><p>${esc(D.about)}</p><a class="text-link" href="/about/">Kenal lebih dekat ↗</a></div></section><section class="casual-section"><div class="casual-photo">${photo(D.casualPhoto,'Foto nonformal — di luar meja kerja')}</div><div><span class="eyebrow">DI LUAR BINGKAI</span><h2>Lebih dari sekadar<br>hasil akhir.</h2><p>Bagi saya, kreativitas dan teknologi saling melengkapi. Sudut pandang baru bisa datang dari mana saja—di balik kamera, di depan layar, atau saat mencoba sesuatu yang belum pernah dilakukan.</p><a class="text-link" href="/skills/">Lihat keahlian & tools ↗</a></div></section>${cta()}</main>`;}
function gallery(path){const creative=path==='creative';const categories=['Semua',...new Set(D.projects.filter(p=>p.path===path).map(p=>p.category))];return `<main id="main" tabindex="-1" class="category ${path}"><section class="page-intro"><a class="back" href="/">← Beranda</a><span class="eyebrow">${creative?'01 — VISUAL & CERITA':'02 — LOGIKA & SOLUSI'}</span><h1>${creative?'Media <em>& Kreatif.</em>':'Teknologi <i>& Programming.</i>'}</h1><p>${creative?'Visual yang bercerita, dari momen pertama hingga sentuhan terakhir.':'Solusi yang terstruktur, dari baris kode hingga perangkat yang bergerak.'}</p></section>${!creative?robotFeature(D.projects.find(p=>p.id==='robotika')):''}<section class="work-section"><div class="section-line"><h2>${creative?'Eksplorasi visual':'Eksplorasi teknologi'}</h2><span>PORTOFOLIO / ${creative?'KREATIF':'TEKNOLOGI'}</span></div><p class="content-note">${creative?'Koleksi visual — Karya dari balik layar':'Proyek UAS dan ruang untuk karya berikutnya.'}</p><div class="filters" aria-label="Filter proyek">${categories.map(c=>`<button class="${activeFilter===c?'selected':''}" data-filter="${c}" aria-pressed="${activeFilter===c}">${c}</button>`).join('')}</div><div class="project-grid">${D.projects.filter(p=>p.path===path&&(activeFilter==='Semua'||p.category===activeFilter)).map(card).join('')}</div></section><section class="tools-section"><span class="eyebrow">PERANGKAT DI BALIK PROSES</span><h2>${creative?'Dari ide menjadi visual.':'Dari konsep menjadi solusi.'}</h2>${toolGrid(path)}</section>${cta(path)}</main>`;}
function about(){return `<main id="main" tabindex="-1"><section class="page-intro"><span class="eyebrow">TENTANG SAYA</span><h1>Mahasiswa yang belajar.<br><em>Kreator yang berkarya.</em></h1></section><section class="casual-section"><div class="casual-photo">${photo(D.formalPhoto,'Foto formal Mochamad Fajar Maulana')}</div><div><h2>Mochamad<br>Fajar Maulana.</h2><p class="student-badge">${esc(D.education.status)} ${esc(D.education.major)}<br><span>${esc(D.education.institution)}</span></p><p>${esc(D.about)}</p><p>${esc(D.learningFocus)}</p><a class="button" href="/contact/">Mari berkenalan ↗</a></div></section><section class="casual-section reversed"><div class="casual-photo">${photo(D.casualPhoto,'Foto nonformal Mochamad Fajar Maulana')}</div><div><span class="eyebrow">DI BALIK PROSES</span><h2>Terus belajar.<br>Terus mencoba.</h2><p>${esc(D.collaborationFocus)}</p></div></section>${cta()}</main>`;}
function contact(service){return `<main id="main" tabindex="-1" class="contact-page"><section><span class="eyebrow">KONTAK</span><h1>Ide Anda.<br><em>Langkah kita</em><br>berikutnya.</h1><p>Ceritakan kebutuhan, ruang lingkup, dan waktu yang Anda rencanakan.</p><div class="socials">${[['Instagram',D.instagram],['LinkedIn',D.linkedin],['WhatsApp',D.whatsapp?'https://wa.me/'+D.whatsapp:'']].map(([n,u])=>u?`<a target="_blank" rel="noopener" href="${esc(u)}">${n} ↗</a>`:`<span>${n}<small>Segera tersedia</small></span>`).join('')}</div></section><form id="contact-form"><label>Nama<input required name="name" placeholder="Nama lengkap Anda" autocomplete="name"></label><label>Email<input required type="email" name="email" placeholder="nama@email.com" autocomplete="email"></label><label>Kebutuhan<select name="service"><option value="Kreatif" ${service==='creative'?'selected':''}>Jasa Media & Kreatif</option><option value="Teknologi" ${service==='tech'?'selected':''}>Jasa Teknologi & Programming</option><option>Kolaborasi lainnya</option></select></label><label>Pesan<textarea required name="message" rows="5" placeholder="Ceritakan ide proyek Anda..."></textarea></label><button class="button" type="submit">${D.whatsapp?'Lanjutkan ke WhatsApp':D.email?'Buka aplikasi email':'Siapkan pesan'} ↗</button><p class="form-note">${D.whatsapp||D.email?'Pesan dibuka di aplikasi pilihan Anda untuk dikirim.':'Kontak pemilik belum diisi. Anda dapat menyiapkan dan menyalin pesan, tetapi pesan belum dapat dikirim.'}</p><div id="form-result" role="status"></div></form></main>`;}


function robotFeature(p) {
 const a=p.gallery;
 return `<section class="robot-feature" aria-label="Proyek UAS IoT">
  <div class="robot-copy"><span class="eyebrow">PROYEK UAS / ROBOTIKA & IOT</span><h2>Ruang terpantau.<br><i>Aktivitas tercatat.</i></h2><p>${esc(p.description)}</p><div class="detail-tags">${p.tools.slice(0,4).map(t=>`<span>${esc(t)}</span>`).join('')}</div><a class="text-link" href="/proyek/robotika/">Lihat proyek <span aria-hidden="true">↗</span></a></div>
  <div class="robot-stage-wrap"><div class="robot-stage" data-depth tabindex="0" role="group" aria-label="Showcase kedalaman 3D dokumentasi UAS. Gunakan tombol panah untuk mengubah sudut.">
   <div class="robot-stack"><figure class="depth-hardware"><span class="stage-caption">01 / HARDWARE</span>${photo(a[0].src,a[0].alt,'',a[0])}</figure><figure class="depth-dashboard"><span class="stage-caption">02 / WEB DASHBOARD</span>${photo(a[1].src,a[1].alt,'',a[1])}</figure><span class="depth-chip">ESP32 <span>→</span> WEB <span>→</span> TELEGRAM</span></div>
  </div><div class="depth-controls"><span>Dokumentasi asli · tampilan berlapis</span><button data-depth-reset type="button" aria-label="Reset sudut showcase">Reset sudut ↺</button></div></div>
 </section>`;
}
function detail(p) {
 return `<main id="main" tabindex="-1" class="project-page"><section class="page-intro"><a class="back" href="/${p.path}/">← ${p.path==='tech'?'Teknologi':'Kreatif'}</a><span class="eyebrow">${esc(p.category)} / ${p.sample?'CONTOH KONTEN':'PROYEK UAS'}</span><h1>${esc(p.title)}</h1><p>${esc(p.description)}</p><div class="detail-tags">${p.tools.map(t=>`<span>${esc(t)}</span>`).join('')}</div></section>
 ${p.id==='robotika'?robotFeature(p):''}
 <section class="detail-gallery" aria-label="Dokumentasi proyek">${(p.gallery||[{src:p.image,alt:p.alt||p.title,srcset:p.srcset,caption:p.title}]).map(a=>`<figure>${a.src?`<button class="image-button" data-lightbox="${esc(a.src)}" data-alt="${esc(a.alt)}" aria-label="Perbesar ${esc(a.caption||a.alt)}">${photo(a.src,a.alt,'',a)}<span class="open-project" aria-hidden="true">↗</span></button>`:photo('',a.alt)}<figcaption>${esc(a.caption||a.alt)}</figcaption></figure>`).join('')}</section>
 ${p.before&&p.image?`<section class="editing-comparison"><label for="comparison">Geser untuk membandingkan sebelum dan sesudah</label><input id="comparison" data-compare type="range" min="0" max="100" value="50"><div class="comparison">${photo(p.image,'Sesudah editing')}${photo(p.before,'Sebelum editing','before-image')}</div></section>`:''}
 <section class="project-result"><h2>${p.sample?'Tentang karya':'Hasil proyek'}</h2><p>${esc(p.result)}</p>${p.source?`<small>${esc(p.source)}</small>`:''}<div class="project-links">${p.demo?`<a class="text-link" href="${esc(p.demo)}" target="_blank" rel="noopener">Lihat demo ↗</a>`:''}${p.github?`<a class="text-link" href="${esc(p.github)}" target="_blank" rel="noopener">GitHub ↗</a>`:''}</div></section>${cta(p.path)}</main>`;
}
function skills() {return `<main id="main" tabindex="-1"><section class="page-intro"><span class="eyebrow">SKILL & TOOLS</span><h1>Ide yang luas.<br><em>Perangkat yang tepat.</em></h1><p>Perangkat kreatif dan teknis yang mendukung proses kerja saya.</p></section><section class="tools-section"><h2>Media & Kreatif</h2>${toolGrid('creative')}<h2 class="tools-heading">Teknologi & Programming</h2>${toolGrid('tech')}</section>${cta()}</main>`;}

return {render:(route,p)=>header(route)+(p?detail(p):route==='home'?home():route==='creative'||route==='tech'?gallery(route):route==='about'?about():route==='skills'?skills():contact(''))+footer()};
}
